### ISSUE TITLE
Incorrect Definition for CLT

### ISSUE THREAD

**Issue by aknauft** [danielkunin/Seeing-Theory#1]
Current statement: 
> The central limit theorem (CLT) states that a sufficiently large number of means of samples of independent random variables, each with a finite expected value and variance, will approach the normal distribution.

The means of samples won't converge to the normal distribution *unless your sample size is large enough*... Consider samples of size n=1: the sampling distribution will match whatever the underlying population distribution is, including whether it is normal or not.

Try: 
> The central limit theorem (CLT) states that the means from sufficiently large samples of independent random variables (each with a finite expected value and variance) will follow a normal distribution.

**Comment by danielkunin** [comment]
@aknauft Thanks for the more accurate and clearer statement.  Updated!
